apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eas-weather-rs-dev
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: eas-weather-rs
    releaseName: eas-weather-rs
    namespace: eas-weather-rs-dev
    valuesInline:
      image:
        repository: ghcr.io/shyuen/eas-weather-rs-server
        tag: b0b91f8-d183.26.1
      replicaCount: 1
      config:
        logging:
          trace_level: debug
