apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eas-weather-rs-staging
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: eas-weather-rs
    releaseName: eas-weather-rs
    namespace: eas-weather-rs-staging
    valuesInline:
      image:
        repository: ghcr.io/shyuen/eas-weather-rs-server
        tag: b0b91f8-d183.26.1
      replicaCount: 2
      config:
        logging:
          format: json
          trace_level: info
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
