apiVersion: v1
kind: Service
metadata:
  name: {{ include "eas-weather-rs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eas-weather-rs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "eas-weather-rs.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http