{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eas-weather-rs.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eas-weather-rs.labels" . | nindent 4 }}
{{- end }}