apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: eas-weather-rs
    releaseName: eas-weather-rs
    valuesInline:
      image:
        repository: ghcr.io/shyuen/eas-weather-rs-server
        tag: latest
      secrets:
        secretName: eas-weather-rs-secrets